project_name: aactl

env:
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

gomod:
  proxy: false

sboms:
- artifacts: binary

builds:
- binary: aactl
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: ./cmd/aactl
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}}
  - -s -w -X main.commit={{.ShortCommit}}
  - -s -w -X main.date={{.Date}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: GoogleCloudPlatform
    name: aactl
  prerelease: auto

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - readme
    - typo
    - "version bump"

brews:
- tap:
    owner: GoogleCloudPlatform
    name: homebrew-aactl
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/GoogleCloudPlatform/aactl"
  description: "Vulnerability management tool."
  folder: Formula
  license: "Apache-2.0"
  test: |
    system "#{bin}/aactl --version"

nfpms:
- file_name_template: "aactl-{{.Version}}_{{.Os}}-{{.Arch}}"
  homepage: https://github.com/GoogleCloudPlatform/aactl/
  description: "Vulnerability management tool."
  maintainer: aactl developers <aactl@thingz.io>
  license: Apache 2.0
  vendor: aactl developers
  formats:
  - deb
  - rpm
  bindir: /usr/bin

universal_binaries:
- replace: true
  name_template: 'aactl'
