# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aactl < Formula
  desc "Vulnerability management tool."
  homepage "https://github.com/GoogleCloudPlatform/aactl"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.2/aactl_0.4.2_darwin_all"
    sha256 "0ddbbc66d2b694acaa262a51320a0aea64bdc44d3b0837df06e1ad84f73e093a"

    def install
      bin.install "aactl_0.4.2_darwin_all" => "aactl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.2/aactl_0.4.2_linux_amd64"
      sha256 "5fd706bdf768cc094a517d445295698ab5427635d501f5bae22a2ee69b62d693"

      def install
        bin.install "aactl_0.4.2_linux_amd64" => "aactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.2/aactl_0.4.2_linux_arm64"
      sha256 "962570288c794529c139c0fc87150412628e392be877181bd9af9f7bbba89f8d"

      def install
        bin.install "aactl_0.4.2_linux_arm64" => "aactl"
      end
    end
  end

  test do
    system "#{bin}/aactl --version"
  end
end
