# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aactl < Formula
  desc "Vulnerability management tool."
  homepage "https://github.com/GoogleCloudPlatform/aactl"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.3/aactl_0.4.3_darwin_all"
    sha256 "2e6bacc53b90b2e60e18ebb2c05ca5fb8c8d5d8d5b66d14f44c96448a457ad91"

    def install
      bin.install "aactl_0.4.3_darwin_all" => "aactl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.3/aactl_0.4.3_linux_amd64"
      sha256 "f4630bc181719822ed45d135e63dd491a10f6526a0295186bf26fde1d9fe1a20"

      def install
        bin.install "aactl_0.4.3_linux_amd64" => "aactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoogleCloudPlatform/aactl/releases/download/v0.4.3/aactl_0.4.3_linux_arm64"
      sha256 "195f921aa68ed8f44a06157c10623302a13496f20a0c50101ad29ff7ab43d718"

      def install
        bin.install "aactl_0.4.3_linux_arm64" => "aactl"
      end
    end
  end

  test do
    system "#{bin}/aactl --version"
  end
end
