# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _LOCATION: us-central1
  _IMG_NAME: node-demo
  _IMG_VERSION: v0.0.4

steps:

# Build image
- id: build
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  dir: examples/cloud-build
  args:
  - -c
  - |
    docker build \
      -t "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}" \
      .

# Publish image
- id: publish
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - build
  dir: examples/cloud-build
  args:
  - -c
  - |-
    docker push "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}"
    docker image inspect "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}" \
      --format '{{index .RepoDigests 0}}' > image-digest.txt
    cat image-digest.txt

- id: scan
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: /bin/bash
  dir: examples/cloud-build
  waitFor:
  - publish
  args:
  - -c
  - |-
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
    grype --add-cpes-if-none -s AllLayers -o json --file report.json $(cat image-digest.txt)

- id: import
  waitFor:
  - scan
  name: gcr.io/cloud-builders/aactl
  dir: examples/cloud-build
  args:
  - vulnerability
  - --project=$PROJECT_ID
  - --source=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_IMG_NAME}:${_IMG_VERSION}
  - --file=report.json

images:
- ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMG_NAME:${_IMG_VERSION}

options:
  # Verify generation of attestations and provenance metadata for this build.
  # Otherwise, GCB generates provenance for global builds only.
  requestedVerifyOption: VERIFIED
