#!/bin/bash

set -euo pipefail

project=$1
digest=$2

snyk container test --app-vulns \
                    --json-file-output=report.json $digest

bin/aactl --debug vulnerability --project cloudy-labz \
                                --source $digest \
                                --file report.json

gcloud artifacts docker images describe $digest \
    --project $project \
    --show-package-vulnerability \
    --format json | jq -r .
