# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: sign-image

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: false
        type: string
        default: 'v1.13.1'
      scan_severity:
        description: 'Error on vulnerability scan severity'
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'

permissions:
  contents: read

jobs:

  sign:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d  # v1.0.0
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65  # v3.0.1
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      run: |
        set -euo pipefail
        cosign version
        reg=$(echo ${{ inputs.image_digest }} | cut -d/ -f1)
        cosign login ${reg} --username=oauth2accesstoken --password=${{ steps.auth.outputs.access_token }}

    - name: Generate Keys
      run: |
        set -euo pipefail
        COSIGN_PASSWORD=$(openssl rand -base64 12)
        cosign generate-key-pair

    - name: Attest Image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        set -euo pipefail
        cosign sign ${{ inputs.image_digest }} \
            --force \
            --key cosign.key \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }} \
            -a tag=${{ env.GITHUB_REF_NAME }}

    - name: Attest Image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        set -euo pipefail
          cosign verify \
          --key cosign.pub \
          ${{ inputs.image_digest }}
